export const defaultData = {
	global: {
		activeItems: [],
		iconEnabled: true,
		iconPosition: "right",
		activeIcon: "arrow-right",
		activeIconType: "solid",
		inactiveIcon: "arrow-down",
		inactiveIconType: "solid",
		activeIconClassName: "size-6",
		inactiveIconClassName: "size-6",
		labelClassName: "",
		activeLabelClassName: "",
		headerClassName: "",
		activeHeaderClassName: "",
		contentClassName: "",
		accordionClassName: "",
	},
	items: [
		{
			id: "item-1",
			headerLabel: "Accordion 1",
			content: "Content 1",
			iconEnabled: true,
			iconPosition: "right",
			iconClassName: "size-6",
			activeIconClassName: "size-6",
			activeIcon: "arrow-right",
			inactiveIcon: "arrow-down",
			disabled: false,
			headerClassName: "",
			labelClassName: "",
			activeLabelClassName: "",
			activeHeaderClassName: "",
			contentClassName: "",
			accordionClassName: "",
		},
	],
};
